In [58]:
import numpy as np
import pandas as pd

<p style="text-align:center; color:red; font-weight:bold; font-size:20px;">
  DataTypes and Attribute
</p>


In [3]:
# numpy main data type is ndarray

In [5]:
ar1 = np.array([1,2,3])
ar1

array([1, 2, 3])

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr4  = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
ar1.shape

(3,)

In [46]:
arr3.shape

(3, 3)

In [48]:
arr4.shape

(2, 3, 3)

In [49]:
ar1.ndim , arr2.ndim, arr3.ndim , arr4.ndim

(1, 2, 2, 3)

In [51]:
ar1.dtype , arr3.dtype

(dtype('int64'), dtype('int64'))

In [55]:
ar1.size , arr2.size , arr3.size , arr4.size

(3, 6, 9, 18)

In [56]:
type(ar1), type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [81]:
#create a data frame from numpy array
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

<p style="text-align:center; color:red; font-weight:bold; font-size:20px;">
  Creating Arrays
</p>

In [85]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [86]:
ones.shape

(3,)

In [89]:
ones2 = np.ones((2,3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [93]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
arranges_array = np.arange(0,10,2)

In [95]:
arranges_array

array([0, 2, 4, 6, 8])

In [99]:
random = np.random.randint(0,10,size = (3,5))
random

array([[7, 9, 1, 7, 3],
       [4, 0, 1, 2, 0],
       [1, 7, 3, 2, 1]])

In [101]:
random2 = np.random.random((4,5))
random2

array([[0.03050075, 0.89706365, 0.30895096, 0.46828995, 0.82195811],
       [0.5305896 , 0.86463663, 0.79645819, 0.46399974, 0.26484561],
       [0.42459966, 0.89984255, 0.19785265, 0.07917703, 0.74196876],
       [0.53189681, 0.86662525, 0.09989034, 0.16659037, 0.01086469]])

In [102]:
random2.shape

(4, 5)

In [103]:
random3 = np.random.rand(3,4)
random3

array([[0.97016978, 0.13873264, 0.39389736, 0.80032464],
       [0.22375456, 0.86987076, 0.62789686, 0.81452286],
       [0.87769275, 0.0299446 , 0.02657519, 0.86831683]])

In [114]:
np.random.seed(3) #what random.seed(n) does is that random numbers genrated remain same even if we re-run the command
random4 = np.random.randint(0,10,size = (5,3))
random4

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

<p style="text-align:center; color:red; font-weight:bold; font-size:20px;">
  Viewing Arrays and Matrices
</p>

In [115]:
np.unique(random4)

array([0, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ar1

array([1, 2, 3])

In [117]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [128]:
ar1

array([1, 2, 3])

In [121]:
arr2[0]

array([1, 2, 3])

In [126]:
arr3[0] , arr3.shape

(array([1, 2, 3]), (3, 3))

In [124]:
arr4[0] , arr4.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (2, 3, 3))

In [129]:
ar1[:2]

array([1, 2])

In [137]:
arr2[1:,1]

array([5])

In [135]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
arr3[:,2]


array([3, 6, 9])

In [143]:
arr3[1:,1]

array([5, 8])

In [144]:
arr4.shape


(2, 3, 3)

In [145]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [150]:
arr4[1:,1:,1]

array([[14, 17]])

<p style="text-align:center; color:red; font-weight:bold; font-size:20px;">
  Broadcasting and reshaping and transposing
</p>

In [153]:
arr2*ar1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [154]:
arr2*arr3 #this error is on purpose

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [155]:
arr2.shape , arr3.shape


((2, 3), (3, 3))

In [159]:
arr2.reshape(2,1,3) *arr3.reshape(1,3,3)

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[ 4, 10, 18],
        [16, 25, 36],
        [28, 40, 54]]])

In [163]:
#lets see transpose
arr5 = np.array([[1,2,3],[4,5,6]])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
arr5.shape

(2, 3)

In [166]:
arr5.T , arr5.T.shape

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 (3, 2))

In [174]:
#letsee dot-product
np.random.seed(3)
mat1 = np.random.randint(0,10,size = (3,2))
mat2 = np.random.randint(0,10,size = (2,2))
mat1.shape , mat2.shape


((3, 2), (2, 2))

In [177]:
mat3 = np.dot(mat1 , mat2)

In [178]:
mat3.shape

(3, 2)

<p style="text-align:center; color:red; font-weight:bold; font-size:20px;">
  Sorting arrays
</p>

In [189]:
np.random.seed(3)
arr7  = np.random.randint(0,10,size = (3,3))

In [190]:
arr7

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9]])

In [192]:
arr8 = np.sort(arr7)
arr8

array([[3, 8, 9],
       [0, 8, 8],
       [3, 5, 9]])

<p style="text-align:center; color:red; font-weight:bold; font-size:20px;">
  Image->Numpy array
</p>

<img src="numpy-images/panda.png">

In [199]:
from matplotlib.image import imread
panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [200]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [202]:
panda.shape , panda.size

((2330, 3500, 3), 24465000)

In [205]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="numpy-images/car-photo.png">

In [209]:
car = imread("numpy-images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [210]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [211]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)